sudo: required
services:
  - docker

before_install:
  - docker build -t igortas/docker-react -f dockerfile.dev .

script:
 - docker run -e CI=true igortas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket-name: 'elasticbeanstalk-us-east-2-377860696336'
  bucket-path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'